// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: grpc.proto

package grpcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPC_Process_FullMethodName                    = "/grpcproto.GRPC/Process"
	GRPC_BidirectionalStreamProcess_FullMethodName = "/grpcproto.GRPC/BidirectionalStreamProcess"
	GRPC_ClientStreamProcess_FullMethodName        = "/grpcproto.GRPC/ClientStreamProcess"
	GRPC_ServerStreamProcess_FullMethodName        = "/grpcproto.GRPC/ServerStreamProcess"
)

// GRPCClient is the client API for GRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type GRPCClient interface {
	// 定义单次请求方法
	Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// 双向流传输方法
	BidirectionalStreamProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
	// 客户端流传输方法
	ClientStreamProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error)
	// 服务端流传输方法
	ServerStreamProcess(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
}

type gRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCClient(cc grpc.ClientConnInterface) GRPCClient {
	return &gRPCClient{cc}
}

func (c *gRPCClient) Process(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GRPC_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCClient) BidirectionalStreamProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPC_ServiceDesc.Streams[0], GRPC_BidirectionalStreamProcess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPC_BidirectionalStreamProcessClient = grpc.BidiStreamingClient[Request, Response]

func (c *gRPCClient) ClientStreamProcess(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPC_ServiceDesc.Streams[1], GRPC_ClientStreamProcess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPC_ClientStreamProcessClient = grpc.ClientStreamingClient[Request, Response]

func (c *gRPCClient) ServerStreamProcess(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPC_ServiceDesc.Streams[2], GRPC_ServerStreamProcess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPC_ServerStreamProcessClient = grpc.ServerStreamingClient[Response]

// GRPCServer is the server API for GRPC service.
// All implementations must embed UnimplementedGRPCServer
// for forward compatibility.
//
// 定义服务
type GRPCServer interface {
	// 定义单次请求方法
	Process(context.Context, *Request) (*Response, error)
	// 双向流传输方法
	BidirectionalStreamProcess(grpc.BidiStreamingServer[Request, Response]) error
	// 客户端流传输方法
	ClientStreamProcess(grpc.ClientStreamingServer[Request, Response]) error
	// 服务端流传输方法
	ServerStreamProcess(*Request, grpc.ServerStreamingServer[Response]) error
	mustEmbedUnimplementedGRPCServer()
}

// UnimplementedGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCServer struct{}

func (UnimplementedGRPCServer) Process(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedGRPCServer) BidirectionalStreamProcess(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreamProcess not implemented")
}
func (UnimplementedGRPCServer) ClientStreamProcess(grpc.ClientStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamProcess not implemented")
}
func (UnimplementedGRPCServer) ServerStreamProcess(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamProcess not implemented")
}
func (UnimplementedGRPCServer) mustEmbedUnimplementedGRPCServer() {}
func (UnimplementedGRPCServer) testEmbeddedByValue()              {}

// UnsafeGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCServer will
// result in compilation errors.
type UnsafeGRPCServer interface {
	mustEmbedUnimplementedGRPCServer()
}

func RegisterGRPCServer(s grpc.ServiceRegistrar, srv GRPCServer) {
	// If the following call pancis, it indicates UnimplementedGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPC_ServiceDesc, srv)
}

func _GRPC_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPC_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServer).Process(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPC_BidirectionalStreamProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCServer).BidirectionalStreamProcess(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPC_BidirectionalStreamProcessServer = grpc.BidiStreamingServer[Request, Response]

func _GRPC_ClientStreamProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCServer).ClientStreamProcess(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPC_ClientStreamProcessServer = grpc.ClientStreamingServer[Request, Response]

func _GRPC_ServerStreamProcess_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCServer).ServerStreamProcess(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPC_ServerStreamProcessServer = grpc.ServerStreamingServer[Response]

// GRPC_ServiceDesc is the grpc.ServiceDesc for GRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.GRPC",
	HandlerType: (*GRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _GRPC_Process_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalStreamProcess",
			Handler:       _GRPC_BidirectionalStreamProcess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStreamProcess",
			Handler:       _GRPC_ClientStreamProcess_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamProcess",
			Handler:       _GRPC_ServerStreamProcess_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
